### ISSUE TITLE
Questionnaire Scores not coming through in Kibana

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#10]
## User Story

As a analyst, I want PHQ and APEI data required by LSBU2 to be logged in Elasticsearch/Kibana so I can easily collate it for reporting to the LSBU researchers

## Acceptance Criteria.

We need to log the following information in Elasticsearch/Kibana against the user uuid

- [x] Questionnaire responses, or at least their score value.
  - Ideally all responses should be logged, but we could just log fully completed questionnaires
  - We need scores for each question, as well as the total score for completed questionnaires
- [x] Which questionnaire is being taken, and which instance, e.g. APEI-5, PHQ-3, etc
- [x] Datetime user completed question or full questionnaire each time.
- [x] Whether user completed questionnaire on Day -1/0/+1 within the available window
  - We will need to log datetime the user consented at in order to do this, it will then be calculated by logstash as part of changes for #116

## Definition of Done
- [x] Questionnaire responses are visible in Kibana
- [x] Which Questionnaire Instance these responses relate to is apparent
- [x] Day questionnaire was taken on, within +/-1 day window is visible in Kibana
- [x] All logged against user uuid

- [x] Tested on Dev
- [x] Tested on Prod

**Comment by eddieTomo** [comment]
@remihellotomo  this can be closed both here and on the main `tomo` board as we have deprecated PHQs

**Comment by remihellotomo** [comment]
Closed due to deprecated PHQs

**Comment by eddieTomo** [comment]
Re-opened as this will be needed as part of LSBU Stage 2 readiness work

**Comment by eddieTomo** [comment]
Logging for both APEI and PHQ has been raised as issues https://github.com/ActivateMedia/tomo/issues/1031 and https://github.com/ActivateMedia/tomo/issues/1032

**Comment by eddieTomo** [comment]
updated Acceptance Criteria to reflect changes to our approach since LSBU1

**Comment by remihellotomo** [comment]
@eddieTomo to track this completion with issues ActivateMedia/tomo#1031 and ActivateMedia/tomo#1032 and update the LSBU2 document.

**Comment by eddieTomo** [comment]
N.B. the work to calculate the `day window` the questionnaire was taken on has already been completed as part of [ActivateMedia/tomo#1044](https://app.zenhub.com/workspaces/tomo-master-5a031a357a51840f4da62f2a/issues/activatemedia/tomo/1044) :)

**Comment by eddieTomo** [comment]
All the work for this has been completed and is now live as of 31st March 2020
