### ISSUE TITLE
Ensure Tomo App meets colour contrast requirements

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#103]
##  Summary

As the NHS, I want Tomo to comply with standardized colour contrast requirements so that I can be sure the app has good readability

**Q 7.1 of DAQs - **
Does the colour contrast of the text on your native app comply with WCAG 2.0 AA level requirements?
>To be considered for the apps library, all text in your app must have a contrast ratio of at least 4.5:1 as detailed in the WCAG guideline 1.4.3 https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html
>Please adjust the design of your app, so that all text has a contrast ratio of at least 4.5:1 as detailed in the WCAG guideline 1.4.3 https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

##  Acceptance Criteria

- [x] Get Design to collate a full set of design standards and colour pallettes used in the app.  Ask if they know if we already meet required standards
- [x] Submit colour palette to ORCHA contact for preliminary assessment of contrast rations
- [ ] Create issues to redesign app if required by ORCHA/NHS

##  Definition of Done

- [ ] ORCHA Preliminary assessment suggests our colour palettes meet the requirements
- [x] Colour palette is documented in full in Supporting Evidence folder
- [x] Colour palette is referenced in DAQ

**Comment by remihellotomo** [comment]
Tomo/Activate issue 970 in the Backlog as of today, to be in progress as of Monday.

**Comment by remihellotomo** [comment]
970 has been completed and closed, with remaining work to be done by @eddieTomo

**Comment by eddieTomo** [comment]
We've submitted to ORCHA and are awaiting their comments,I'll close and create new issued for the work they raise
