### ISSUE TITLE
Calculate Day Questionnaire Completed On & Test No in Elasticsearch

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#114]
# New Feature/Improvement Request

##  Summary

As an analyst, I want to know if a user completed either an APEI or a PHQ on the day it was due, the day before, or day after, so that I can report that information to LSBU

##  Acceptance Criteria

- [x] Need completion of https://github.com/ActivateMedia/tomo/issues/1031 and https://github.com/ActivateMedia/tomo/issues/1032 first
- [x] Add scripted field in Elasticsearch or logstash that calculates D-1/D=0/D+1 to question completion log
- [x] Add code to script questionnaire instance number based on {ts} - {reference timestamp} value.  e.g D13-15 = `APEI-2`

```groovy
if ( ( ( remainder: ( (doc.value.ts - doc.value.reference_ts ) / 86400 ) % 7 ) >= 1) && ((remainder: ( ( doc.value.ts - doc.value.reference_ts ) / 86400 ) % 7 ) =< 2 ) ) 
  { ctx._source.Q_day: 'D-1'}
  else if  ( ( ( remainder: ( ( doc.value.ts - doc.value.reference_ts ) / 86400 ) % 7 ) >= 0 ) && ( ( remainder: ( ( doc.value.ts - doc.value.reference_ts ) / 86400 ) % 7 ) =< 1 ) ) 
  { ctx._source.Q_day: 'D=1'}
  else if  ( ( ( remainder: ( ( doc.value.ts - doc.value.reference_ts ) / 86400 ) % 7 ) >= 6 ) && ( ( remainder: ( ( doc.value.ts - doc.value.reference_ts ) / 86400 ) % 7 ) =< 7 ) ) 
  { ctx._source.Q_day: 'D+1'}
```

##  Definition of Done

- [x] Elasticsearch Logs include whether user completed on `D-1`, `D=0`, or `D+1` in field `Q_day`
- [x] Can run analysis in Kibana to see when users generally complete each test type
- [x] Tested on Dev
- [x] Tested & Live on Prod

##### 📅 Release Deadline: By end 2019

**Comment by eddieTomo** [comment]
I have written scripting in logstash to caluclate this and will be able to do this once 
https://app.zenhub.com/workspaces/tomo-master-5a031a357a51840f4da62f2a/issues/activatemedia/tomo/895
https://app.zenhub.com/workspaces/tomo-master-5a031a357a51840f4da62f2a/issues/activatemedia/tomo/1031
https://app.zenhub.com/workspaces/tomo-master-5a031a357a51840f4da62f2a/issues/activatemedia/tomo/1032
are completed by dev

**Comment by eddieTomo** [comment]
following code to be added to logstash configuration changes #116

```
  if [reference_ts] and [ts] {
    ruby {
        id => "q_taken_window_calc"
        code =>  "
            if
              ( ( ( ( (event.get('[ts]') - event.get('[reference_ts]') ) ) / 86400 ) % 7 ) >= 1 &&
              ( ( ( (event.get('[ts]') - event.get('[reference_ts]') ) ) / 86400 ) % 7 ) < 2 )
                return event.set('[stats][q_taken_window]', -1)
            elsif
              ( ( ( ( (event.get('[ts]') - event.get('[reference_ts]') ) ) / 86400 ) % 7 ) >= 0 &&
              ( ( ( (event.get('[ts]') - event.get('[reference_ts]') ) ) / 86400 ) % 7 ) < 1 )
                return event.set('[stats][q_taken_window]', 0)
            elsif
              ( ( ( ( (event.get('[ts]') - event.get('[reference_ts]') ) ) / 86400 ) % 7 ) >= 6 &&
              ( ( ( (event.get('[ts]') - event.get('[reference_ts]') ) ) / 86400 ) % 7 ) < 7 )
                return event.set('[stats][q_taken_window]', 1)
            else
                return event.set('[stats][q_taken_window]', 9999)
            end
            "
      }
      ruby {
        id => "q_taken_day_calc"
        code => "
          event.set('[stats][q_day_taken]', (((event.get('[ts]') - event.get('[reference_ts]'))/86400).floor))
        "
      }
   }
```

**Comment by eddieTomo** [comment]
the code for this is live on dev, but requires [#1031](https://app.zenhub.com/workspaces/tomo-master-5a031a357a51840f4da62f2a/issues/activatemedia/tomo/1031) and [#1032](https://app.zenhub.com/workspaces/tomo-master-5a031a357a51840f4da62f2a/issues/activatemedia/tomo/1032) to be completed first to check

**Comment by eddieTomo** [comment]
This has been implemented in logstash but awaits #1031 and #1032 as above

**Comment by remihellotomo** [comment]
Issue has been raised and is in the Backlog - ActivateMedia/tomo#1171

**Comment by eddieTomo** [comment]
This is now live in Production as of 31st March 2020
