### ISSUE TITLE
Time to complete on-boarding info in Elasticsearch/Kibana

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#126]
##  Summary

As an analyst I want the timestamp info for onboarding started & completed at to be pushed to Kibana, so I can assess how long users are taking to complete it.

##  Acceptance Criteria

Devs
When a user completes onboarding (`context.onboarding:false`), push the following information from the db for the user to the Elasticsearch log
  - [x] `onboarding_startedAt
  - [x] `onboarding_completedAt`

@eddieTomo 
 - [x] Adjust logstash ruby filter to calculate time between these values
 - [x] Remove onboarding elapsed filter
 - [x] Add new timestamp filters to elasticsearch index mapping so they can be parsed properly

@gianpaolom
  - [x] Upload new logstash pipeline

##  Definition of Done

Elasticsearch log when a user completes onboarding includes:
 - [x] Time onboarding started at in human readable formant
 - [x] Time onboarding completed at in human readable format
 - [x] Time taken to complete onboarding

##### 📅 Release Deadline:

**Comment by remihellotomo** [comment]
@eddieTomo to find and record actionable ticket for Activate please.

**Comment by eddieTomo** [comment]
@remihellotomo this is an low-priority enhancement for work that i already have a more clunky solution to.  :)

Bug issue #123 does need to be fixed though for even the clunky solution to work, and we should bring that ticket over to the Activate

**Comment by eddieTomo** [comment]
This has been completed following the implementation of #123 and is now calculated by logstash.  The following keys are available in Kibana:

`context.onboarded: no` - start of onboarding
`context.onboarded: yes` - end of onboarding
`context.time_to_onboard: *` - time taken for that user to onboard; is the difference in log timestamps between `context.onboarded: yes` and `context.onboarded: no`
