### ISSUE TITLE
Context.key variables not logging to Elasticsearch

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#130]
## Expected behaviour

`context.key`  (or any other variable stated in the script using the `context` command) should log to Elasticsearch as per our documentation
https://github.com/ActivateMedia/tomo/wiki/Dialogue-Writing-YAML#command-context

## Actual behaviour

`context.key` does not log to to Elasticsearch.

N.b. `input.key` in the scripts (such as in `Activity Selector #1`) already logs to `context.key` in Elasticsearch and this is expected as per #1004

- Because we do not currently log interactions in the Explore modal, we have no way of easily identifying when a user selects an activity via this route
- Because the message in `activity_selector #0` is variable, the search query to find all instances of [do any activity] or a specific activity (e.g. "Dance around") is needlessly complex.  Being able to search for
`context.key: "do_activity"` (as expected from documentation) would solve this
- This functionality will also be useful once we have push notifications fully working, as we will want to log when a user enters from a notification (using the relevant dialogue message) even if the user then does not select one of the related chat inputs (e.g. navigates straight to explore instead)

## Steps to reproduce

Explore modal -> Select an activity -> Receive `activity_selector #0` -> do nothing.

--- 
Example using `activity_selector.yml`

```YAML
0:
  activity_selector:
    - "[Great!|Excellent!|Cool!|You got this!|Good one!] ${userSelectedActivity.name} and [take|snap] a [photo|picture]"
  context:
    key: do_activity
  user_context_suggestion_accepted:
  anchor: 1
```

Expected Log in Elasticsearch (example has been shortened to illustrate the key point):
```JSON
{
  "host": "127.0.0.1"
  "sender": "Tomo",
  "user": "be64770a-88ae-4a34-8803-1ffbb780e9d8",
  "message": "Great! Dance around and take a photo",      // <---- ${userSelectedActivity.name} rendered correctly in message to user
  "context": {
    "key": "do_activity"      // <----  context.key is logged
  }
}
```

Actual log received in Elasticsearch (again, shortened):
```JSON
{
  "host": "127.0.0.1"
  "sender": "Tomo",
  "user": "be64770a-88ae-4a34-8803-1ffbb780e9d8",
  "message": "Great! Dance around and take a photo"      // <---- ${userSelectedActivity.name} rendered correctly in message to user
}      // <---- context.key is not logged at all
```

**Comment by eddieTomo** [comment]
for @remihellotomo to review so can be raised as a new issue with Activate

**Comment by remihellotomo** [comment]
Raised as a new issue as of 21/1 - ActivateMedia/tomo#1172. Thank you!

**Comment by eddieTomo** [comment]
Now closed and completed with Activate
