### ISSUE TITLE
Name temporarily lost in Profile after Consent

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#133]
# Bug Report Template

### Expected behaviour

Once user sets `user_name` during onboarding, it always be displayed in `Profile` modal and should be used whenever called in dialogues in the `Chat` modal

### Actual behaviour

Name is lost in `Profile` after onboarding (but during Consent)
Name is still correctly used in chats even when not displayed in Profile
A re-log/session refresh fixes this problem
Present in `1.0.4` and `1.0.5`

### Steps to reproduce

New User -> Onboarding -> User Name -> Check Profile - > Name Present
Continue Onboarding -> Reach Consent -> Check Profile -> Name Lost
Finish Consent -> Continue Chat -> Correct Name used in Chat -> Check Profile -> Name Still Missing
Logout -> Log back in -> Check Profile -> Name Present Again

| Stage | Chat Modal | Profile Modal |
|--------|---------------|----------------| 
|  Onboarding | ![name_input_at_onboard.png](https://images.zenhubusercontent.com/5b7d90377c781616ae083c58/6a21cb80-ae85-4ea3-9cf2-61957e7b1932) | ![name_in_profile_at_onboard.png](https://images.zenhubusercontent.com/5b7d90377c781616ae083c58/9a987509-6c3e-40d9-ba75-69921cbad9c7) |
| Consent | ![name_still_in_chat_consent.jpg](https://images.zenhubusercontent.com/5b7d90377c781616ae083c58/2d6162b9-52b9-4821-9236-91da36c46ecc) | ![name_lost_profile_consent.jpg](https://images.zenhubusercontent.com/5b7d90377c781616ae083c58/e97653fb-e7dd-4e1b-87c2-5ceb2cc46ce4)

**Comment by eddieTomo** [comment]
Occured for eddie.p.heywood+droid1v0v5@gmail.com on Honor 9

To check with different user on Samsung A20

**Comment by eddieTomo** [comment]
Checked with `eddie.p.heywood+droid1v0v5loss@gmail.com on Samsung A20 and same issue encountered

| Stage | Chat Modal | Profile Modal |
|--------|---------------|----------------| 
|  Onboarding | ![eph+droid1v05loss_onboard_chat.jpg](https://images.zenhubusercontent.com/5b7d90377c781616ae083c58/9fd40c95-5b3e-4634-b53b-7be5e45b68bf) | ![eph+droid1v05loss_onboard_profile.jpg](https://images.zenhubusercontent.com/5b7d90377c781616ae083c58/33b80987-1da1-4131-b184-498b2cdf8dec) |
| Consent | ![eph+droid1v05loss_consent_chat.jpg](https://images.zenhubusercontent.com/5b7d90377c781616ae083c58/778cce93-81e3-4a2a-8b61-28155c7f6d42) | ![eph+droid1v05loss_consent_profile.jpg](https://images.zenhubusercontent.com/5b7d90377c781616ae083c58/c6301c1b-8b50-4d74-a203-6cec4ae46d9c) |
| Session Refresh | ![eph+droid1v05loss_return_chat.jpg](https://images.zenhubusercontent.com/5b7d90377c781616ae083c58/1d91374e-b863-4c99-a1c5-ebfbc254e303) | ![eph+droid1v05loss_return_profile.jpg](https://images.zenhubusercontent.com/5b7d90377c781616ae083c58/02f8cd03-4c74-496a-b093-155e138b506e) |

**Comment by eddieTomo** [comment]
@remihellotomo please review and decide if you want to bring over to the main board

**Comment by remihellotomo** [comment]
This `user_name lost` issue is in two parts: 1) New User and 2) Returning User.  I've checked with your user `eddie.p.heywood+droid1v0v5loss@gmail.com` (Returning user) in `1.0.6` and user_name `X627` is correctly in `Profile` (though not in `Unpaid` chat). 

Since `1050` is reserved for our Onboarding chapters, `New User user_name lost` should be fixed with it.  NB: 1) Consent is part of New User instance and 2) As seen above, Consent dialogue recalls the name, whilst the Profile does not, which is less problematic.

Future bugs for `user_name lost` should be labelled as `New User` vs. `Returning User`, knowing that `New User` instance will be problematic until `1050`. Any `Returning User user_name lost` should continue to be flagged separately. 

Thanks @eddieTomo

**Comment by eddieTomo** [comment]
Considered under ticket https://github.com/ActivateMedia/tomo/issues/1201

Closed for now as this is a low priority issue
