### ISSUE TITLE
Develop a naming system for dialogues

### ISSUE THREAD

**Issue by fbalsaud** [remihellotomo/Tomo-Office#26]
Choose one of the 2 templates below:

## User Story
As a <type of user>, I want <a goal>, so that <benefit>.

**Comment by remihellotomo** [comment]
@fbalsaud I think this could be improved, for sure, so can you have a think about what other systems exist and what you're envisioning of a) what it should do and b) what it shouldn't do?

**Comment by remihellotomo** [comment]
For the time being, dialogue names should specify: 1) if the user experiencing them is a new user (_NU) or returning user (_RU) as this is important for the user journey; 2) Subject should be from user standpoint and not use backend jargon (Start_Session, Activity_Selector); 3) Words broken up with '_' for ease; 4) No &'s as requested by GP (instead, use '-', i.e., PHQ-APEI_RU.yml); 5) End all dialogue names with '.yml' (however, GP has confirmed that in the dialogues themseleves, we do not need to use the .yml, we can simply say the name, i.e., script_name: start_session).  I have created a Wiki page for this for the time being.  Any changes will be updated by PM.

**Comment by remihellotomo** [comment]
@eddieTomo to add our key conventions to the above wiki, since these are dialogue conventions we should be sticking to.
