### ISSUE TITLE
Consent Modal & Dialogue

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#42]
##  Summary

As a company, we want to ask users to opt-in to data sharing with clinical research partners as part of onboarding, so we can collect data to help validate the effectiveness of Tomo

##  Acceptance Criteria

- [x] Opt-in wording drafted and agreed with LSBU/Laywers
- [x] Opt in dialogue written as tomo-script
- [x] Dialogue explains benefit of study from a user perspective
- [x] Dialogue explains what sort of data we'll study and why
- [x] Dialogue explains what commitments are required from user as part of opt-in (3 months, regular PHQ & SWLS)
- [x] Dialogue has a clear "opt-in/i consent" vs. "no thanks" option

##  Definition of Done

- [x] Tested and confirmed on dev
- [x] Tested and confirmed on prod
- [x] Dialogue results in correct tagging/recording of consent

##### 📅 Release Deadline:

**Comment by remihellotomo** [comment]
Design has been agreed and acceptance criteria met, awaiting implementation inside the app - issue 952 in Tomo/Activate

**Comment by eddieTomo** [comment]
Live in App as of 4.2
