### ISSUE TITLE
Add week counter to log fields

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#43]
##  Summary

As a clinical researcher, I want to see how many weeks it has been since a user created their account so that I can easily compare users at a similar point in their progression regardless of when they actually signed up for the app

##  Acceptance Criteria

- [x] Add `week_no` field to data logs based on [ log timestamp - user created timestamp ]
- [x] Week is measured relative to user first login to app.  
- [x] Weeks start at 0 and increment by 1 every 7 days (i.e Day 8 = start of Week 1)
- [x] 'Days' for counting week purposes should start at 00:00:00.000 

A user who creates an account at 15:10 on Thursday reaches Week 2 at 00:00:00.000 on Thursday of the following week.

##  Definition of Done

- [x] Week field comes through in Kibana logs and increments correctly per acceptance criteria above
- [x] Tested and confirmed on dev
- [x] Tested and confirmed on prod

##### 📅 Release Deadline:

**Comment by remihellotomo** [comment]
This has been removed as a part of the LSBU 2 start date (July) due to time, but may be incorporated into in the future. For now, @eddieTomo will be responsible for extracting this for LSBU.

**Comment by eddieTomo** [comment]
i have scripted code in logstash to do this, it is reliant on https://app.zenhub.com/workspaces/tomo-master-5a031a357a51840f4da62f2a/issues/activatemedia/tomo/895 being completed by Dev

**Comment by eddieTomo** [comment]
Following code to be added to logstash configuration changes #116

```
  if [firstlogin_ts] {
  # Calculate full weeks since first log in
  ruby {
      id => "week_no_calc"
      code => "event.set('[cohort][completed_weeks]', ((DateTime.now.to_time.to_i - event.get('[firstlogin_ts]'))/604800).floor)"
    }
  # Also calculate days since first login
  ruby {
      id => "day_no_calc"
      code => "event.set('[cohort][completed_days]', ((DateTime.now.to_time.to_i - event.get('[firstlogin_ts]'))/86400).floor)"
    }
  }
```

**Comment by eddieTomo** [comment]
This is now completed on production
