### ISSUE TITLE
PHQ & A-PEI for LSBU2

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#45]
# New Feature/Improvement Request

##  Summary

As a clinical researcher, I want clinically validated forms of evaluating Tomo's user experiences in the app so I can produce scientifically viable results.

##  Acceptance Criteria

- [X] Determine what measures we might wish to use - PHQ & A-PEI
- [X] Determine how often these measures should be tracked for each user.  PHQ @ Week 0|1, 6 & 12. A-PEI @ Week 0|1, 2, 4, 8 & 12
- [x] Write logic and dialogue that measures these for users who have chosen to opt-in only
- [x] Ensure users can view their scores in their history
- [x] Ensure we have mechanisms to detect 'low' scores that warrant signposting towards mental health resources or medical intervention.
- [x] ~~Individual~~ and summated scores for these measures push through to user logs in ES/Kibana

##  Definition of Done

Users who have not opted in do not receive clinical measure dialogues
Users who have opted in do receive clinical measure dialogues at correct intervals
Users with low score are signposted accordingly
Scores come through in logs

##### 📅 Release Deadline:

**Comment by eddieTomo** [comment]
Likely PHQ at week 1 and week 12
SWLS at week 1, 2, 4, 8, 12

These activites can be postponed a timeslot or two but not skipped/deleted and must be done +/- 24h of due date.

**Comment by eddieTomo** [comment]
Discussed with @fbalsaud on the previous implementation methods for LSBU1.
Possible implementation for delivering clinical questionnaires are:
- Dialogue script (used for PHQ in LSBU1)
- Hardcoded questionnaire modal that requires new build for each questionnaire and cannot be changed easily (used for SWLS for in LSBU1)
- Generalised questionnaire modal that was partly envisaged for LSBU1 but abandoned due to lack of time

Discussed with Paolo how the previous implementions of the PHQ & SWLS worked, and a potential generalised 'questionnaire' solution that would enable us to run the PHQ and SWLS, as well as be extensible for future questionnaires we might wish to include in the app (e.g. mood, corporate/clinical surveys, user feedback etc).  

Paolo outlined the technical requirements that would be required to achieve a general solution:
- New architecture, API, and associated entities to support general questionnaire modal and data storage of user responses across several questionnaires
- Decide what to do with old PHQ data - affected users are almost, if not certainly nil
- Design in-app questionnaire modal that can deliver all expected questionnaire formats & response types.
- Some form of translator/converter so questionnaires can be written as YAML script but present correctly via in-app modal
- Ensure valid data logging in Kibana - a problem with previous implementations

Paolo commented that even with the more simple hardcoded or dialogue options to just get the PHQ & SWLS in for LSBU2, we would need to:
- extend the current API
- fix the current kibana data logging issues
- design & build the in-app interfaces (which were problematic in LSBU1 and have since been deprecated from app)
All of which is likely around 30-50% of the work compared to a more general solution.

Discussed all of above with @remihellotomo and @fbalsaud who agreed that, depending on workload and complexity, the general solution seems the best approach and would likely be needed in future anyway, but will need to discuss with and get feedback from dev team on how much work/time this might be and if we can deliver this within the LSBU2 timeframe

**Comment by remihellotomo** [comment]
Thanks @eddieTomo great to see it all together.  I'll update with what I've done here.

**Comment by remihellotomo** [comment]
The prep work around design, dialogues and notifications for APEI and PHQ has been completed. We have decided that these will not exist within Explore for consented users to perform/select/skip, but rather, will be shown at entry when opening the app on the days which they can be completed.  This is a more direct approach, with less user influence, but means that we'll be more likely to have them complete it as it's required before they can use Tomo as they would generally.  The next phase of this is to implement it.

**Comment by eddieTomo** [comment]
As of 4.2 PHQ and APEI are live in the app, and results are stored in DB, but logging to Kibana and notifications are still outstanding

**Comment by remihellotomo** [comment]
As of 4.2.2, @eddieTomo and I have agreed that the logging of summated scores is the priority and currently what's been achieved for 4.2.2 on September 16, but not individual scores. Therefore, I have stricken out `Individual summation` from the AC. 

Still TBD are:
ActivateMedia/tomo/issues/986
ActivateMedia/tomo/issues/987
ActivateMedia/tomo/issues/1032
ActivateMedia/tomo/issues/1031
ActivateMedia/tomo/issues/890
ActivateMedia/tomo/issues/891

**Comment by eddieTomo** [comment]
@remihellotomo if the devs can push the `stats` block either at completion, or at timeout for each questionnaire instance, this should cover both individual and summated question scores anyway :)

**Comment by eddieTomo** [comment]
This is now working following completion of 1031 and 1032 and is live on production as of 31st March 2020
