### ISSUE TITLE
Morning, Before Notifications Logic

### ISSUE THREAD

**Issue by fbalsaud** [remihellotomo/Tomo-Office#51]
# New Feature/Improvement Request

##  Summary

We would like to remind users about scheduled habits *before* they do the habit. However, this is problematic for morning habits. Users may find being reminded of their to-do list for the coming morning is disruptive for sleep. Is it possible to mitigate this? Or should we tie morning habit reminders to the start of the morning slot?

in the event that we introduce customisable time slots, this issue will become one of 'what are we encouraging users to do'.

##  Other links or relevant information

Supplementary documentation, links to code documentation etc

##  Acceptance Criteria

Usually more detailed technical requirements of what needs to be done to achieve this.

##  Definition of Done

How would the {user} test or be aware that this feature is active and working?  Usually non-technical compared to above.

##### 📅 Release Deadline: What milestone or app version release do you need this implemented by?

**Comment by remihellotomo** [comment]
@fbalsaud please have a look at issue 839 in Activate/Tomo as we need to address this in the short term, before we can think about the long-term goal for 'before' habits and mornings.

**Comment by remihellotomo** [comment]
As of 4.1.3 in App, we have tied morning habit reminders to the start of the morning slot to mitigate any sleep disruption.

**Comment by remihellotomo** [comment]
For a detailed list of what our app timings and notification timings are at the moment, see https://github.com/ActivateMedia/tomo/wiki/App-Timings-&-Notifications-2019
I will close this for now since customisable notifications are already in the Tomo/Activate backlog.
