### ISSUE TITLE
Reduce monthly subscription price to £9.99

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#54]
# New Feature/Improvement Request

##  Summary

As Tomo, we want Tomo's monthly subscription price to be in line with competitors, to make us more attractive to users. 
 
##  Acceptance Criteria

- [x] Reduce price for monthly subscription to £9.99 in App Store Connect
- [x] Update App Store T&Cs
- [x] Update website T&Cs to reflect this
- [x] Update T&Cs within subscription section of app.

##  Definition of Done

Live and confirmed on dev
Live confirmed on prod
Live in app store
Live on www.hellotomo.co.uk

##### 📅 Release Deadline:

**Comment by eddieTomo** [comment]
Done but pending approval of next build from Apple until changes to T&Cs will be live on App Store

**Comment by remihellotomo** [comment]
This is now complete as build 4.1.12 was approved with the T&Cs successfully implemented and live.
