### ISSUE TITLE
Increase Course Package duration to 92 days

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#55]
##  Summary

As Tomo, we want our Course Package to include 3 months access, so course users are encouraged to use Tomo App for the full length of the research study.

##  Acceptance Criteria

- [ ] Increase length of Course Package on get.hellotomo.co.uk pages to 92 days months 
- [ ] Amend Stripe API call to reflect increase duration of course package

##  Definition of Done

Tested and confirmed on dev
Live on prod.
N.B. Do not create test payments on production stripe instance!

##### 📅 Release Deadline:

**Comment by eddieTomo** [comment]
updated acceptance criteria to 92 days not 3 months and single course package offering

**Comment by remihellotomo** [comment]
August 15 update:
Issue is in Dev-Sprint as issue https://github.com/ActivateMedia/tomo/issues/944

**Comment by remihellotomo** [comment]
ActivateMedia/tomo#944 has been completed and is live for users on 4.2.1 (Sept 5th)
