### ISSUE TITLE
Delay asking for payment till end of 1 week trial

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#56]
Summary of issue or user story if appropriate:

As a potential customer, I want to try Tomo properly before I am asked for money, so I can see the value in what I am paying for.

##  Acceptance Criteria

- [x] Shorten trial period to 1 week.
- [x] Move asking for payment during free trial until end of 1 week trial period
- [x] Amend T&Cs to reflect this in app store page
- [x] Amend T&Cs to reflect this in subscription section of App
- [x] Amend T&Cs to reflect this on www.hellotomo.co.uk 

##  Definition of Done

Tested and confirmed on dev
Tested and confirmed on prod
Live on app store page
Live on www.hellotomo.co.uk

##### 📅 Release Deadline:

**Comment by remihellotomo** [comment]
As of 4.1.12, the acceptance criteria has been met. Due to the Apple product rejection, and the app crashing, we extended the trial period to 30 days to ensure that users were not asked to pay and then experience the crash.  This will be moved back to 7 days come June 11th. This is now closed.
