### ISSUE TITLE
Display PHQ & A-PEI in All Your Habits for opt-in users

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#62]
##  Summary

As a user who has opted in to the LSBU2 study, I want to have the questionnaires I have to do displayed in my list of habits so I remember what I committed to.

##  Acceptance Criteria

- [ ] Display PHQ  as a non-deletable, non editable habit in a opt_in user's "all your habits "sections of Explore.
- [ ] Display A-PEI as a non-deletable, non editable habit in a opt_in user's "all your habits "sections of Explore.

##  Definition of Done

- [ ] PHQ & A-PEI Visible in All Your Habits section
- [ ] Cannot be deleted by a user
- [ ] Schedule cannot be edited by a user
- [ ] Tested and confirmed on dev
- [ ] Tested and confirmed on prod

##### 📅 Release Deadline:

**Comment by remihellotomo** [comment]
This has been removed as a part of the LSBU 2 start date (July) due to time, but may be incorporated into habits in the future.  This is now closed.
