### ISSUE TITLE
Prevent course users from buying a second course

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#69]
##  Summary

As a user who completes a course, I want a simplified subscription screen in the app so that I don't buy the same product twice

##  Other links or relevant information

Issue created based off discussions of user flows in https://github.com/ActivateMedia/tomo/issues/860

User Flows:
https://app.mural.co/t/hellotomo2717/m/hellotomo2717/1549979113572/d2a618de28199a1c5feb662e2465d131f92a2708

- Can/Should we roll users who purchase a Course via Stripe (or indeed App Store) onto a monthly sub?

##  Acceptance Criteria

- [x] Implement logic to ensure user who has already had a course subscription cannot purchase these options again.
- [x] Design explanation of this to user in-app

##  Definition of Done

- [x] User who finished a course subscription only has monthly subscription option presented to them in subscription screen.

##### 📅 Release Deadline:

**Comment by remihellotomo** [comment]
@eddieTomo Do you think it would be helpful (or not) for Design to have this piece of information for buying courses within the app?

Aka, do you think we should be designing with this in mind or can we get away with holding off on it?

**Comment by eddieTomo** [comment]
@remihellotomo as per my slack, i'd say hold off for now, we don't need it till we need it

**Comment by remihellotomo** [comment]
As of 4.1.12, users who have bought an App and Course Package can not purchase another and will be asked, at expiry, will be faced with an unpaid, expired dialogue (and see App Subscription available to buy with a 'Continue your journey with Tomo' explanation in Your Plan).  Similarly, those who have purchased an App Subscription can purchase a one-off Course Add on ('Boost your plan anytime'), after which, they can not buy it again.
