### ISSUE TITLE
Campaign Tracking Codes

### ISSUE THREAD

**Issue by remihellotomo** [remihellotomo/Tomo-Office#7]
## User Story

As a marketing and sales client, I want to set up tracking for the app to link to Tomo's Google Analytics & App Store Connect; as well as tag unique referral campaign codes in Kibana, so that Tomo can understand user retention and acquisition by campaign.

## Acceptance Criteria

Tomo can see exactly how many customers came through each campaign code and how long they stayed, etc.  

This system needs to be in place so to work for future campaigns and campaign codes.

From a product perspective, I'd like to use this data to gain user data.  All tracking should be as hidden as possible so as not to interfere with the user experience.

Background:
https://support.google.com/analytics/answer/3389142?hl=en and

https://developers.google.com/analytics/devguides/collection/analyticsjs/linker

## Definition of Done
Tracking and Kibana fully working.

#### 🗓 Expected Date:

**Comment by eddieTomo** [comment]
UTM identifiers for campaigns on iOS apps - assume these need to be added into iOS code (dev) and then passed through to kibana via logstash/elasticsearch & mapped (dev/eddie)
https://developers.google.com/analytics/devguides/collection/ios/v3/campaigns

**Comment by eddieTomo** [comment]
Passing parameters via rules in Auth0
https://auth0.com/learn/powering-user-analytics-identity/

**Comment by eddieTomo** [comment]
implemented by dev
