### ISSUE TITLE
Re-design options on get.hellotomo.co.uk

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#73]
# New Feature/Improvement Request

##  Summary

As a marketer I want the options on get.hellotomo.co.uk to be the same as in-app purchases so users can purchase via either route

##  Acceptance Criteria
- [x] Remove `Set` and `Go` courses from get.hellotomo.co.uk
- [x] Redesign copy & presentation of 'Ready' course in line with app look
- [x] Revise page copy for "Course Selection" and "Select your package" in page header
- [x] Add `Monthly subscription` option, similar to in-app option
- [x] `Course only` bolt on is NOT available by this route - only in-app

This issue will then drive the development work for #74 and #75

##  Definition of Done

Design mockup finished and confirmed.

##### 📅 Release Deadline: What milestone or app version release do you need this implemented by?

**Comment by remihellotomo** [comment]
In progress with Tomo/Active - issue #862

**Comment by eddieTomo** [comment]
Completed as per issue https://app.zenhub.com/workspaces/tomo-master-5a031a357a51840f4da62f2a/issues/activatemedia/tomo/999
