### ISSUE TITLE
Add monthly subscription option to Stripe gateway

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#74]
##  Summary

As a user, I want to be able to buy a monthly subscription via get.hellotomo.co.uk, so the same options are available to me however I buy Tomo

##  Acceptance Criteria

- [ ] Add monthly subscription option to selection page
- [ ] Add monthly subscription option to stripe
- [ ] Add support for monthly subscription to payment page
- [ ] Coupons can be used to discount a monthly subscription.
- [ ] Updates user profile in backend systems to paid status and expiry date

##  Definition of Done

- [ ] User can buy a monthly subscription via get.hellotomo.co.uk
- [ ] Monthly subscription rolls around every 30 days
- [ ] User receives an email receipt each time their subscription rolls around
- [ ] User receives a link at sign up and on each email receipt to cancel their subscription

##### 📅 Release Deadline: What milestone or app version release do you need this implemented by?

**Comment by remihellotomo** [comment]
Combined with #73 - and in Tomo/Activate issue 862

**Comment by remihellotomo** [comment]
As of yesterday, it was decided that the monthly Subscription would not be available (along with the course add on) via get.hellotomo.co.uk - just App and Course Package, so this will now be closed.  The acceptance criteria above should apply for App and Course Package users, however.
