### ISSUE TITLE
Amend Price & Duration of App & Course Package

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#75]
##  Summary

As a customer, I want the price and duration of the course package to be the same on get.hellotomo.co.uk as in the app, so I don't feel unfairly charged.

##  Acceptance Criteria

- [x] Adjust Stripe charge for course package to £23.99
- [ ] Increase duration of course package to 92 days

##  Definition of Done

- [ ] User buying course package via get.hellotomo.co.uk is charged £23.99 and can see their subscription expiry date in the app as +92 days from initial purchase.

##### 📅 Release Deadline: What milestone or app version release do you need this implemented by?

**Comment by remihellotomo** [comment]
Amended the acceptance criteria from 98 days duration to 92 days.  Updated issue 862 on Tomo/Activate, which is already in progress, so this is too.

**Comment by eddieTomo** [comment]
Remainder of this ticket is covered under issue #55 so closing
