### ISSUE TITLE
Update links to website in app

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#85]
# New Feature/Improvement Request

##  Summary

As a user, I want links in the Tomo app to direct me to the correct place on the Tomo website, so I can access the information I need easily

##  Acceptance Criteria

Update links within Tomo app as follows

### In-app Links

| App Section | App Text | Old website link | New website link |
|---|---|---|---|
| Onboarding | User Terms | hardcoded into app | Update text from `https://www.hellotomo.co.uk/terms` |
| Onboarding | Privacy Policy | hardcoded into app | Update text from `https://www.hellotomo.co.uk/privacy-policy` |
| Profile| Terms and Conditions | `https://www.hellotomo.co.uk/terms` | NO CHANGE |
| Profile | Privacy Policy | `https://www.hellotomo.co.uk/privacy-policy` | NO CHANGE |
| Profile | Feedback | `https://www.hellotomo.co.uk/support` | NO CHANGE |
| Profile | Mental Health Support | `https://www.hellotomo.co.uk/faq#where-can-i-go` | `https://www.hellotomo.co.uk/help` |
| Subscription | What does this mean? | `https://www.hellotomo.co.uk/faq#corporate-license` | --- |
| History - PHQ Score | What does this mean? | `https://www.hellotomo.co.uk/faq#what-is-a-phq` | ---|
| Will need one for APEI | --- |--- |---|

### New website FAQ link master reference

https://docs.google.com/spreadsheets/d/1YNvAJktnqPCmhw4PBV8X0NHKZIMgrY_8k0un54XM-hI/edit?usp=sharing

 

##  Definition of Done

All links in Tomo app direct to correct new pages & anchors

##### 📅 Release Deadline: What milestone or app version release do you need this implemented by?

**Comment by remihellotomo** [comment]
As part of 4.1.12, we have implemented these changes to our links inside the app.  This is now live, so this is now closed.
